"""Field configuration for the template-v2 book form."""

# These values are used for options that remain visible in the DOCX. The
# renderer applies double strikethrough to options that were not selected.
CHECKBOX_CHAR = "■"
UNCHECKED_CHAR = "□"

SECTIONS: list[dict] = [
    {
        "title": "書籍基本資料",
        "layout": "grid",
        "fields": [
            {"placeholder": "bookTitleChi",
                "label": "書名 (中)", "source_key": "title_chi", "type": "text", "included_in_ai_prompt": True},
            {"placeholder": "bookTitleEng",
                "label": "書名 (英)", "source_key": "title_eng", "type": "text", "included_in_ai_prompt": True},
            {"placeholder": "seriesName", "label": "叢書系列", "source_key": "series",
                "type": "text", "included_in_ai_prompt": True},
            {"placeholder": "publisher", "label": "出版社", "source_key": "publisher",
                "type": "text", "included_in_ai_prompt": True},
            {"placeholder": "author", "label": "作者", "source_key": "author_name",
                "type": "text", "included_in_ai_prompt": True},
            {"placeholder": "isbn", "label": "ISBN", "source_key": "isbn",
                "type": "text", "included_in_ai_prompt": True},
            {"placeholder": "priceHKD", "label": "港幣定價", "source_key": "price_hkd",
                "type": "positive_integer", "included_in_ai_prompt": True},
            {"placeholder": "priceTWD", "label": "台幣定價", "source_key": "price_twd",
                "type": "positive_integer", "included_in_ai_prompt": True},
            {"placeholder": "publishDate", "label": "出版日期 (dd/mm/yyyy)", "source_key": "publication_date",
             "type": "date", "included_in_ai_prompt": True, "row_group": "pub_format"},
            {"placeholder": "moFormat", "label": "開度", "source_key": "", "type": "text",
                "options": ["", "16", "25", "32", "64"], "row_group": "pub_format"},
            {"placeholder": "bookCategories", "label": "圖書分類",
                "source_key": "category", "type": "text", "included_in_ai_prompt": True},
            {"placeholder": "bookColor", "label": "印刷用色", "source_key": "print_color",
                "type": "text", "included_in_ai_prompt": True},
            {"placeholder": "bookBinding", "label": "裝幀", "source_key": "binding",
                "type": "text", "included_in_ai_prompt": True},
            {"placeholder": "numOfPages", "label": "頁數", "source_key": "page_count",
                "type": "text", "included_in_ai_prompt": True},
            {"placeholder": "targetAudience", "label": "讀者群",
                "source_key": "target_audience", "type": "text", "included_in_ai_prompt": True},
            {"placeholder": "firstEdition", "label": "初版",
                "type": "option", "option_group": "edition", "option_mode": "single",
                "option_value": "firstEdition", "default": True},
            {"placeholder": "revisedEdition", "label": "改版",
                "type": "option", "option_group": "edition", "option_mode": "single",
                "option_value": "revisedEdition"},
            {"placeholder": "marketingLevel1", "label": "一級",
                "type": "option", "option_group": "sales_level", "option_mode": "single",
                "option_value": "marketingLevel1", "default": True},
            {"placeholder": "marketingLevel2", "label": "二級",
                "type": "option", "option_group": "sales_level", "option_mode": "single",
                "option_value": "marketingLevel2"},
            {"placeholder": "marketingLevel3", "label": "三級",
                "type": "option", "option_group": "sales_level", "option_mode": "single",
                "option_value": "marketingLevel3"},
            {"placeholder": "langChi", "label": "中文", "type": "option",
                "option_group": "language", "option_mode": "multi", "option_value": "langChi",
                "source_key": "#lang:中文", "included_in_ai_prompt": True},
            {"placeholder": "langTradChi", "label": "繁體", "type": "option",
                "option_group": "language", "option_mode": "multi", "option_value": "langTradChi",
                "source_key": "#lang:繁體", "included_in_ai_prompt": True},
            {"placeholder": "langSimChi", "label": "簡體", "type": "option",
                "option_group": "language", "option_mode": "multi", "option_value": "langSimChi",
                "source_key": "#lang:簡體", "included_in_ai_prompt": True},
            {"placeholder": "langEng", "label": "英文", "type": "option",
                "option_group": "language", "option_mode": "multi", "option_value": "langEng",
                "source_key": "#lang:英文", "included_in_ai_prompt": True},
            {"placeholder": "langOther", "label": "其他", "type": "option",
                "option_group": "language", "option_mode": "multi", "option_value": "langOther",
                "source_key": "#lang:其他", "included_in_ai_prompt": True},
        ],
    },
    {
        "title": "內容簡介", "layout": "full",
        "fields": [{"placeholder": "bookIntro", "label": "內容簡介（請以點列形式列出）", "source_key": "synopsis", "type": "html", "included_in_ai_prompt": True}],
    },
    {
        "title": "本書特色及賣點", "layout": "full",
        "fields": [{"placeholder": "bookHighlights", "label": "本書特色及賣點（請以點列形式列出）", "source_key": "book_highlights", "type": "html", "included_in_ai_prompt": True}],
    },
    {
        "title": "作者簡介", "layout": "full",
        "fields": [{"placeholder": "authorIntro", "label": "作者簡介", "source_key": "author_bio", "type": "html", "included_in_ai_prompt": True}],
    },
    {
        "title": "名人推薦", "layout": "full",
        "fields": [{"placeholder": "endorsements", "label": "名人推薦", "source_key": "endorsements", "type": "html", "included_in_ai_prompt": True}],
    },
    {
        "title": "目錄", "layout": "full",
        "fields": [{"placeholder": "tableOfContents", "label": "目錄", "source_key": "table_of_contents", "type": "html", "included_in_ai_prompt": True}],
    },
]
